# Exported from Render on 2024-12-03T15:50:35Z
services:
- type: web
  name: qpb-ws
  runtime: node
  repo: https://github.com/bladeski/quizpopbang
  plan: free
  envVars:
  - fromGroup: QuizPopBang Prod Variables
  region: frankfurt
  buildCommand: yarn --frozen-lockfile install; yarn build:ws
  startCommand: yarn start:ws
- type: web
  name: quizpopbang
  runtime: node
  repo: https://github.com/bladeski/quizpopbang
  plan: free
  envVars:
  - fromGroup: QuizPopBang Prod Variables
  region: frankfurt
  buildCommand: yarn --frozen-lockfile install; yarn build
  startCommand: node dist/server/entry.mjs
version: "1"
